jobs:
  build-ami:
    name: Build AMI
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone infra repo
      run: 'echo "Cloning repo..."

        git clone https://infra-tech:${{ secrets.INFRA_USER_ACCESS_TOKEN }}@github.com/provectus/kafka-ui-infra.git
        --branch ${{ github.event.inputs.KafkaUIInfraBranch }}

        echo "Cd to packer DIR..."

        cd kafka-ui-infra/ami

        echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV

        echo "Packer will be triggered in this dir $WORK_DIR"

        '
    - continue-on-error: true
      name: Configure AWS credentials for Kafka-UI account
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_AMI_PUBLISH_KEY_ID }}
        aws-region: us-east-1
        aws-secret-access-key: ${{ secrets.AWS_AMI_PUBLISH_KEY_SECRET }}
    - continue-on-error: true
      name: Validate Template
      uses: hashicorp/packer-github-actions@master
      with:
        arguments: -syntax-only
        command: validate
        target: kafka-ui-infra/ami/kafka-ui.pkr.hcl
    - continue-on-error: true
      env:
        PACKER_LOG: 1
      name: Build Artifact
      uses: hashicorp/packer-github-actions@master
      with:
        arguments: -color=false -on-error=abort -var=kafka_ui_release_version=${{
          github.event.inputs.KafkaUIReleaseVersion }}
        command: build
        target: kafka-ui.pkr.hcl
        working_directory: ${{ env.WORK_DIR }}
    - continue-on-error: true
      env:
        AMI_OS_VERSION: amzn2-ami-kernel-5.10-hvm-*-x86_64-gp2
        MP_ROLE_ARN: ${{ secrets.AWS_MARKETPLACE_AMI_ACCESS_ROLE }}
        PRODUCT_ID: ${{ secrets.AWS_SERVER_PRODUCT_ID }}
        RELEASE_NOTES: https://github.com/provectus/kafka-ui/releases/tag/v${{ github.event.inputs.KafkaUIReleaseVersion
          }}
        RELEASE_VERSION: ${{ github.event.inputs.KafkaUIReleaseVersion }}
      if: ${{ github.event.inputs.PublishOnMarketplace == 'true' }}
      name: Publish Artifact at Marketplace
      run: "set -x\npwd\nls -la kafka-ui-infra/ami\necho $WORK_DIR/manifest.json\n\
        export AMI_ID=$(jq -r '.builds[-1].artifact_id' kafka-ui-infra/ami/manifest.json\
        \ | cut -d \":\" -f2)\n/bin/bash kafka-ui-infra/aws-marketplace/prepare_changeset.sh\
        \ > changeset.json\naws marketplace-catalog start-change-set \\\n  --catalog\
        \ \"AWSMarketplace\" \\\n  --change-set \"$(cat changeset.json)\"\n"
name: 'Infra: Release: AWS Marketplace Publisher'
on:
  repository_dispatch:
    types: trigger-ga___aws_publisher.yaml
