jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      env:
        BASE_REF: ${{ github.base_ref }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HEAD_REF: ${{ github.head_ref }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
      if: ${{ github.event_name == 'pull_request' }}
      name: Build and analyze pull request target
      run: './mvnw -B -ntp versions:set -DnewVersion=${{ github.event.pull_request.head.sha
        }}

        ./mvnw -B -V -ntp verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        \

        -Dsonar.projectKey=com.provectus:kafka-ui_backend \

        -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \

        -Dsonar.pullrequest.branch=$HEAD_REF \

        -Dsonar.pullrequest.base=$BASE_REF

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
      if: ${{ github.event_name == 'push' }}
      name: Build and analyze push master
      run: './mvnw -B -ntp versions:set -DnewVersion=$GITHUB_SHA

        ./mvnw -B -V -ntp verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        \

        -Dsonar.projectKey=com.provectus:kafka-ui_backend

        '
name: 'Backend: PR/master build & test'
on:
  repository_dispatch:
    types: trigger-ga___backend.yml
permissions:
  checks: write
  pull-requests: write
