jobs:
  block_merge:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: mheap/github-action-required-labels@v5
      with:
        count: 0
        labels: status/blocked, status/needs-attention, status/on-hold, status/pending,
          status/triage, status/pending-backend, status/pending-frontend, status/pending-QA
        mode: exactly
name: 'Infra: PR block merge'
on:
  repository_dispatch:
    types: trigger-ga___block_merge.yml
