jobs:
  remove:
    if: ${{ (github.event.label.name == 'status/feature_testing' || github.event.label.name
      == 'status/feature_testing_public') || (github.event.action == 'closed' && (contains(github.event.pull_request.labels.*.name,
      'status/feature_testing') || contains(github.event.pull_request.labels.*.name,
      'status/feature_testing_public'))) }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: clone
      run: 'git clone https://infra-tech:${{ secrets.INFRA_USER_ACCESS_TOKEN }}@github.com/provectus/kafka-ui-infra.git
        --branch envs

        '
    - continue-on-error: true
      name: remove env
      run: 'cd kafka-ui-infra/aws-infrastructure4eks/argocd/scripts

        ./delete-env.sh pr${{ github.event.pull_request.number }} || true

        git config --global user.email "infra-tech@provectus.com"

        git config --global user.name "infra-tech"

        git add ../kafka-ui-from-branch/

        git commit -m "removed env:${{ needs.build.outputs.deploy }}" && git push
        || true

        '
name: 'Infra: Feature Testing: Destroy env'
on:
  repository_dispatch:
    types: trigger-ga___branch-remove.yml
