jobs:
  build:
    if: ${{ github.event.label.name == 'status/image_testing' }}
    outputs:
      tag: ${{ steps.extract_branch.outputs.tag }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      id: extract_branch
      name: get branch name
      run: 'tag=''${{ github.event.pull_request.number }}''

        echo "tag=${tag}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      id: build
      name: Build
      run: './mvnw -B -ntp versions:set -DnewVersion=$GITHUB_SHA

        ./mvnw -B -V -ntp clean package -Pprod -DskipTests

        export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args=''${project.version}''
        --non-recursive exec:exec)

        echo "version=${VERSION}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      id: buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: Cache Docker layers
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        path: /tmp/.buildx-cache
        restore-keys: '${{ runner.os }}-buildx-

          '
    - continue-on-error: true
      name: Configure AWS credentials for Kafka-UI account
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: us-east-1
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      id: login-ecr
      name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public
    - continue-on-error: true
      id: docker_build_and_push
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        build-args: 'JAR_FILE=kafka-ui-api-${{ steps.build.outputs.version }}.jar

          '
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        context: kafka-ui-api
        push: false
        tags: public.ecr.aws/provectus/kafka-ui-custom-build:${{ steps.extract_branch.outputs.tag
          }}
    - continue-on-error: true
      name: make comment with private deployment link
      uses: peter-evans/create-or-update-comment@v3
      with:
        body: 'Image published at public.ecr.aws/provectus/kafka-ui-custom-build:${{
          steps.extract_branch.outputs.tag }}

          '
        issue-number: ${{ github.event.pull_request.number }}
name: 'Infra: Image Testing: Deploy'
on:
  repository_dispatch:
    types: trigger-ga___build-public-image.yml
