jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      id: build
      name: Build project
      run: './mvnw -B -ntp versions:set -DnewVersion=$GITHUB_SHA

        ./mvnw -B -V -ntp clean package -DskipTests

        export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args=''${project.version}''
        --non-recursive exec:exec)

        echo "version=${VERSION}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: Cache Docker layers
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        path: /tmp/.buildx-cache
        restore-keys: '${{ runner.os }}-buildx-

          '
    - continue-on-error: true
      name: Build docker image
      uses: docker/build-push-action@v4
      with:
        build-args: 'JAR_FILE=kafka-ui-api-${{ steps.build.outputs.version }}.jar

          '
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        context: kafka-ui-api
        load: true
        platforms: linux/amd64
        push: false
        tags: 'provectuslabs/kafka-ui:${{ steps.build.outputs.version }}

          '
    - continue-on-error: true
      name: Run CVE checks
      uses: aquasecurity/trivy-action@0.12.0
      with:
        exit-code: '1'
        format: table
        image-ref: provectuslabs/kafka-ui:${{ steps.build.outputs.version }}
name: CVE checks docker master
on:
  repository_dispatch:
    types: trigger-ga___cve.yaml
