jobs:
  remove:
    if: ${{ github.event.label.name == 'status/image_testing' || ( github.event.action
      == 'closed' && (contains(github.event.pull_request.labels, 'status/image_testing')))
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: extract_branch
      name: get branch name
      run: 'echo

        tag=''${{ github.event.pull_request.number }}''

        echo "tag=${tag}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Configure AWS credentials for Kafka-UI account
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: us-east-1
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      id: login-ecr
      name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public
    - continue-on-error: true
      id: remove_from_ecr
      name: Remove from ECR
      run: "aws ecr-public batch-delete-image \\\n      --repository-name kafka-ui-custom-build\
        \ \\\n      --image-ids imageTag=${{ steps.extract_branch.outputs.tag }} \\\
        \n      --region us-east-1\n"
name: 'Infra: Image Testing: Delete'
on:
  repository_dispatch:
    types: trigger-ga___delete-public-image.yml
