jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Check URLs in files
      uses: urlstechie/urlchecker-action@0.0.34
      with:
        exclude_patterns: localhost,127.0.,192.168.
        exclude_urls: https://api.server,https://graph.microsoft.com/User.Read,https://dev-a63ggcut.auth0.com/,http://main-schema-registry:8081,http://schema-registry:8081,http://another-yet-schema-registry:8081,http://another-schema-registry:8081
        file_types: .md
        print_all: false
name: 'Infra: Docs: URL linter'
on:
  repository_dispatch:
    types: trigger-ga___documentation.yaml
