jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
    - continue-on-error: true
      id: set_env_values
      name: Set up environment
      run: 'cat "./kafka-ui-e2e-checks/.env.ci" >> "./kafka-ui-e2e-checks/.env"

        '
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      id: build_app
      name: Build with Maven
      run: './mvnw -B -ntp versions:set -DnewVersion=${{ github.sha }}

        ./mvnw -B -V -ntp clean install -Pprod -Dmaven.test.skip=true ${{ github.event.inputs.extraMavenOptions
        }}

        '
    - continue-on-error: true
      name: Run test suite
      run: './mvnw -B -ntp versions:set -DnewVersion=${{ github.sha }}

        ./mvnw -B -V -ntp -DQASEIO_API_TOKEN=${{ github.event.inputs.qase_token }}
        -Dsurefire.suiteXmlFiles=''src/test/resources/${{ github.event.inputs.test_suite
        }}.xml'' -Dsuite=${{ github.event.inputs.test_suite }} -f ''kafka-ui-e2e-checks''
        test -Pprod

        '
name: 'E2E: Manual suite'
on:
  repository_dispatch:
    types: trigger-ga___e2e-manual.yml
