jobs:
  build-and-test:
    env:
      CI: true
      NODE_ENV: dev
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      uses: pnpm/action-setup@v2.4.0
      with:
        version: 8.6.12
    - continue-on-error: true
      name: Install node
      uses: actions/setup-node@v3.8.1
      with:
        cache: pnpm
        cache-dependency-path: ./kafka-ui-react-app/pnpm-lock.yaml
        node-version: 18.17.1
    - continue-on-error: true
      name: Install Node dependencies
      run: 'cd kafka-ui-react-app/

        pnpm install --frozen-lockfile

        '
    - continue-on-error: true
      name: Generate sources
      run: 'cd kafka-ui-react-app/

        pnpm gen:sources

        '
    - continue-on-error: true
      name: Linter
      run: 'cd kafka-ui-react-app/

        pnpm lint:CI

        '
    - continue-on-error: true
      name: Tests
      run: 'cd kafka-ui-react-app/

        pnpm test:CI

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
      name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} -Dsonar.pullrequest.branch=${{
          github.head_ref }} -Dsonar.pullrequest.base=${{ github.base_ref }}
        projectBaseDir: ./kafka-ui-react-app
name: 'Frontend: PR/master build & test'
on:
  repository_dispatch:
    types: trigger-ga___frontend.yaml
permissions:
  checks: write
  pull-requests: write
