jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      id: build
      name: Build
      run: './mvnw -B -ntp versions:set -DnewVersion=$GITHUB_SHA

        ./mvnw -V -B -ntp clean package -Pprod -DskipTests

        export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args=''${project.version}''
        --non-recursive exec:exec)

        echo "version=${VERSION}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: Cache Docker layers
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        path: /tmp/.buildx-cache
        restore-keys: '${{ runner.os }}-buildx-

          '
    - continue-on-error: true
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      id: docker_build_and_push
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        build-args: 'JAR_FILE=kafka-ui-api-${{ steps.build.outputs.version }}.jar

          '
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        context: kafka-ui-api
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: false
        tags: 'provectuslabs/kafka-ui:${{ steps.build.outputs.version }}

          provectuslabs/kafka-ui:master

          '
    - continue-on-error: true
      name: update-master-deployment
      run: 'git clone https://infra-tech:${{ secrets.INFRA_USER_ACCESS_TOKEN }}@github.com/provectus/kafka-ui-infra.git
        --branch master

        cd kafka-ui-infra/aws-infrastructure4eks/argocd/scripts

        echo "Image digest is:${{ steps.docker_build_and_push.outputs.digest }}"

        ./kafka-ui-update-master-digest.sh ${{ steps.docker_build_and_push.outputs.digest
        }}

        git config --global user.email "infra-tech@provectus.com"

        git config --global user.name "infra-tech"

        git add ../kafka-ui/*

        git commit -m "updated master image digest: ${{ steps.docker_build_and_push.outputs.digest
        }}" && git push

        '
name: 'Master: Build & deploy'
on:
  repository_dispatch:
    types: trigger-ga___master.yaml
