jobs:
  task-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: kentaro-m/task-completed-checker-action@v0.1.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      uses: dekinderfiets/pr-description-enforcer@0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: 'PR: Checklist linter'
on:
  repository_dispatch:
    types: trigger-ga___pr-checks.yaml
permissions:
  checks: write
