jobs:
  charts:
    needs: release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        client-payload: '{"appversion": "${{ needs.release.outputs.version }}"}'
        event-type: prepare-helm-release
        repository: provectus/kafka-ui-charts
        token: ${{ secrets.CHARTS_ACTIONS_TOKEN }}
  release:
    outputs:
      version: ${{steps.build.outputs.version}}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      run: 'git config user.name github-actions

        git config user.email github-actions@github.com

        '
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      id: build
      name: Build with Maven
      run: './mvnw -B -ntp versions:set -DnewVersion=${{ github.event.release.tag_name
        }}

        ./mvnw -B -V -ntp clean package -Pprod -DskipTests

        export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args=''${project.version}''
        --non-recursive exec:exec)

        echo "version=${VERSION}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.7.0
      with:
        file: kafka-ui-api/target/kafka-ui-api-${{ steps.build.outputs.version }}.jar
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.release.tag_name }}
    - continue-on-error: true
      name: Archive JAR
      uses: actions/upload-artifact@v3
      with:
        name: kafka-ui-${{ steps.build.outputs.version }}
        path: kafka-ui-api/target/kafka-ui-api-${{ steps.build.outputs.version }}.jar
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: Cache Docker layers
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        path: /tmp/.buildx-cache
        restore-keys: '${{ runner.os }}-buildx-

          '
    - continue-on-error: true
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      id: docker_build_and_push
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        build-args: 'JAR_FILE=kafka-ui-api-${{ steps.build.outputs.version }}.jar

          '
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        context: kafka-ui-api
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: false
        tags: 'provectuslabs/kafka-ui:${{ steps.build.outputs.version }}

          provectuslabs/kafka-ui:latest

          '
name: 'Infra: Release'
on:
  repository_dispatch:
    types: trigger-ga___release.yaml
