jobs:
  release-serde-api:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      run: 'git config user.name github-actions

        git config user.email github-actions@github.com

        '
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      id: install-secret-key
      name: Install GPG secret key
      run: 'cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import

        '
    - continue-on-error: true
      name: Publish to Maven Central
      run: 'mvn source:jar  javadoc:jar  package  gpg:sign -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE
        }} -Dserver.username=${{ secrets.NEXUS_USERNAME }} -Dserver.password=${{ secrets.NEXUS_PASSWORD
        }} nexus-staging:deploy   -pl kafka-ui-serde-api  -s settings.xml

        '
name: 'Infra: Release: Serde API'
on:
  repository_dispatch:
    types: trigger-ga___release-serde-api.yaml
