jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: release-drafter/release-drafter@v5
      with:
        commitish: ${{ github.event.inputs.branch }}
        config-name: release_drafter.yaml
        disable-autolabeler: true
        version: ${{ github.event.inputs.version }}
name: 'Infra: Release Drafter run'
on:
  repository_dispatch:
    types: trigger-ga___release_drafter.yml
permissions:
  contents: read
