jobs:
  separate-env-remove:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: clone
      run: 'git clone https://infra-tech:${{ secrets.INFRA_USER_ACCESS_TOKEN }}@github.com/provectus/kafka-ui-infra.git
        --branch envs

        '
    - continue-on-error: true
      name: separate environment remove
      run: 'cd kafka-ui-infra/aws-infrastructure4eks/argocd/scripts

        bash separate_env_remove.sh ${{ github.event.inputs.ENV_NAME }}

        git config --global user.email "infra-tech@provectus.com"

        git config --global user.name "infra-tech"

        git add -A

        git commit -m "separate env removed: ${{ github.event.inputs.ENV_NAME }}"
        && git push || true

        '
name: 'Infra: Feature Testing Public: Destroy env'
on:
  repository_dispatch:
    types: trigger-ga___separate_env_public_remove.yml
