jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v8
      with:
        days-before-issue-close: 3
        days-before-issue-stale: 7
        days-before-pr-close: 7
        days-before-pr-stale: 7
        labels-to-remove-when-unstale: status/pending
        only-labels: status/pending
        remove-issue-stale-when-updated: true
        stale-issue-label: status/stale
        stale-issue-message: This issue has been automatically marked as stale because
          no requested feedback has been provided. It will be closed if no further
          activity occurs. Thank you for your contributions.
        stale-pr-label: status/stale
        stale-pr-message: This PR has been automatically marked as stale because no
          requested changes have been applied. It will be closed if no further activity
          occurs. Thank you for your contributions.
name: 'Infra: Close stale issues'
on:
  repository_dispatch:
    types: trigger-ga___stale.yaml
