jobs:
  triage_prs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Label PR
      uses: andymckay/labeler@master
      with:
        add-labels: status/triage
        ignore-if-labeled: true
name: 'Infra: Triage: Apply triage label for PRs'
on:
  repository_dispatch:
    types: trigger-ga___triage_prs.yml
